# This workflow will build and push a web application to Google App Engine when you change your code.

name: Deploy web app to Google App Engine staging

on:
  push:
    branches: [ "staging" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "staging" ]

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for actions/google-app-engine to deploy
      id-token: write # for actions/google-app-engine to deploy
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
        project_id: '${{ secrets.PROJECT_ID }}'
        version: 'staging'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'
      
        
